service: serverless-express-test

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1

package:
  exclude:
    - .git/**
    - test/**
    - README.md
    - node_modules/@aws-crypto/**
    - node_modules/@aws-sdk/**
    - node_modules/aws-sdk/**



functions:
  serverlessTest:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'